apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: mytodoapp
    role: frontend
    env: test
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: mytodoapp
      role: frontend
  template:
    metadata:
      labels:
        app: mytodoapp
        role: frontend
    spec:
      containers:
        - name: frontend
          #image:
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 
    