apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend #name/lable of deployment
  labels:
    app: mytodoapp
    role: api #Pod label for matching
    env: test
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: mytodoapp
      role: api #Actual pod will have role api
  template:
    metadata:
      labels:
        app: mytodoapp
        role: api
    spec:
      containers:
      - name: api
        # image: backend ecr image
        imagePullPolicy: Always
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-sec
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-sec
              key: password
        - name: MONGODB_URI
          value: mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongo-svc:27017/todosdb?authSource=admin
        ports:
        - containerPort: 5000
